using System;

namespace POESKillTree.Stats
{
    // We interpret all nodes as keystones that have some special effect, not just the keystones themselves

    [Flags]
    public enum Keystone
    {
        None                    = 0,

        Acrobatics              = 1 << 0,
        AddersTouch             = 1 << 1,
        AncestralBond           = 1 << 2,
        ArmorMaster             = 1 << 3,
        ArrowDodging            = 1 << 4,
        Bloodless               = 1 << 5,
        BloodMagic              = 1 << 6,
        BreathOfRime            = 1 << 7,
        ChaosInoculation        = 1 << 8,
        Conduit                 = 1 << 9,
        EldritchBattery         = 1 << 10,
        ElementalEquilibrium    = 1 << 11,
        FreezeImmunity          = 1 << 12,
        GhostReaver             = 1 << 13,
        HammerBlows             = 1 << 14,
        HexMaster               = 1 << 15,
        IronGrip                = 1 << 16,
        IronReflexes            = 1 << 17,
        KingOfTheHill           = 1 << 18,
        MinionInstability       = 1 << 19,
        NecromanticAegis        = 1 << 20,
        PainAttunement          = 1 << 21,
        PhaseAcrobatics         = 1 << 22,
        PiercingShots           = 1 << 23,
        PointBlank              = 1 << 24,
        PowerfulBlast           = 1 << 25,
        PurityOfEssence         = 1 << 26,
        ResoluteTechnique       = 1 << 27,
        ShockImmunity           = 1 << 28,
        UnwaveringStance        = 1 << 29,
        VaalPact                = 1 << 30,
        WhispersOfDoom          = 1 << 31,
        ZealotsOath             = 1 << 32
    }

    public enum StatType
    {
        None,

        AccuracyRating,
        AddedChaosMaxDmg,
        AddedChaosMinDmg,
        AddedColdMaxDmg,
        AddedColdMinDmg,
        AddedFireMaxDmg,
        AddedFireMinDmg,
        AddedLightningMaxDmg,
        AddedLightningMinDmg,
        AddedPhysicalMaxDmg,
        AddedPhysicalMinDmg,
        AllResist,
        AoEDamage,
        AoERadius,
        Armor,
        AttackSpeed,
        ArrowSpeed,
        AuraManaReservation,
        AuraRadius,
        AxeAccuracyRating,
        AxeAttackSpeed,
        AxePhysicalDamage,
        BlockAndStunRecovery,
        BlockRecovery,
        BowAccuracyRating,
        BowAttackSpeed,
        BowCriticalStrikeChance,
        BowCriticalStrikeMultiplier,
        BowGemLevel,
        BowPhysicalDamage,
        BowStunDuration,
        BuffDebuffDuration,
        BurnAvoidance,
        BurnChanceOnEnemies,
        BurnDamageOnEnemies,
        BurnDurationOnEnemies,
        CastSpeed,
        ChaosResist,
        ChillAvoidance,
        ChillDuration,
        ChillDurationOnEnemies,
        ClawAccuracyRating,
        ClawAttackSpeed,
        ClawCriticalStrikeChance,
        ClawLifeLeech,
        ClawPhysicalDamage,
        ColdDamage,
        ColdGemLevel,
        ColdResist,
        CriticalDamageTaken,
        CriticalStrikeChance,
        CriticalStrikeMultiplier,
        CurseCastSpeed,
        DaggerAccuracyRating,
        DaggerAttackSpeed,
        DaggerCriticalStrikeChance,
        DaggerCriticalStrikeMultiplier,
        DaggerPhysicalDamage,
        Dexterity,
        DodgeChance,
        DualWieldAccuracyRating,
        DualWieldAttackSpeed,
        DualWieldBlockChance,
        DualWieldPhysicalWeaponDamage,
        DualWieldShieldBlockChance,
        DualWieldWeaponCriticalStrikeChance,
        ElementalDamage,
        ElementalStatusAvoidance,
        EnduranceChargeCount,
        EnduranceChargeDuration,
        EnduranceChargeLifeReg,
        EnemyStunThreshold,
        EnergyShieldCooldownRecovery,
        EnergyShieldFromShield,
        EvasionAndArmorRating,
        EvasionRating,
        FireDamage,
        FireGemLevel,
        FireResist,
        FlaskChargesUsed,
        FlaskLifeRecovery,
        FlaskLifeRecoveryRate,
        FlaskManaRecovery,
        FlaskRecoverySpeed,
        FreezeAvoidance,
        FreezeChanceOnEnemies,
        FreezeDurationOnEnemies,
        FrenzyChargeCount,
        FrenzyChargeDuration,
        FrenzyChargeEvasionRating,
        GemLevel,
        InnerForce,
        Intelligence,
        InterruptAvoidance,
        ItemQuantity,
        ItemRarity,
        Keystone,
        KnockbackChance,
        KnockbackDistance,
        LifeGainOnHit,
        LifeGainOnKill,
        LifeReg,
        LightningDamage,
        LightningGemLevel,
        LightningResist,
        MaceAccuracyRating,
        MaceAttackSpeed,
        MaceCriticalStrikeMultiplier,
        MaceElementalDamage,
        MaceEnemyStunThreshold,
        MacePhysicalDamage,
        ManaCostOfSkills,
        ManaGainOnKill,
        ManaReg,
        MaxColdResist,
        MaxFireResist,
        MaxEnergyShield,
        MaxLife,
        MaxLightningResist,
        MaxMana,
        MaxSkeletons,
        MaxSpectres,
        MaxZombies,
        MeleeGemLevel,
        MeleePhysicalDamage,
        MinionDamage,
        MinionGemLevel,
        MinionLife,
        MovementSpeed,
        OneHandAccuracyRating,
        OneHandAttackSpeed,
        OneHandCriticalStrikeChance,
        OneHandCriticalStrikeMultiplier,
        OneHandPhysicalDamage,
        PhysicalDamage,
        PhysicalLifeLeech,
        PhysicalManaLeech,
        PhysicalReflect,
        PowerChargeCount,
        PowerChargeDuration,
        PowerChargeSpellDamage,
        ProjectileDamage,
        ShieldAllResist,
        ShieldBlockChance,
        ShieldDefences,
        ShockAvoidance,
        ShockChanceOnEnemies,
        ShockDurationOnEnemies,
        SkillDuration,
        SpellBlockChanceFromPhysicalBlockChance,
        SpellCriticalStrikeChance,
        SpellCriticalStrikeMultiplier,
        SpellDamage,
        StaffAccuracyRating,
        StaffAttackSpeed,
        StaffBlockChance,
        StaffGlobalCriticalStrikeChance,
        StaffGlobalCriticalStrikeMultiplier,
        StaffPhysicalDamage,
        StaffStunDuration,
        Strength,
        StunAvoidance,
        StunDurationOnEnemies,
        SwordAccuracyRating,
        SwordAttackSpeed,
        SwordCriticalStrikeMultiplier,
        SwordEnemyBlockChance,
        SwordPhysicalDamage,
        TotemDuration,
        TotemLife,
        TotemRange,
        TrapMineDuration,
        TrapMineLayingSpeed,
        TrapMineTriggerRadius,
        TrapsAllowed,
        TwoHandAccuracyRating,
        TwoHandAttackSpeed,
        TwoHandCriticalStrikeChance,
        TwoHandPhysicalDamage,
        TwoHandStunDuration,
        WandAccuracyRating,
        WandAddedColdDamage,
        WandAddedFireDamage,
        WandAddedLightningDamage,
        WandAttackSpeed,
        WandDamagePerPowerCharge,
        WandElementalDamage,
        WandPhysicalDamage,
        WeaponColdDamage,
        WeaponElementalDamage,
        WeaponFireDamage,
        WeaponLightningDamage,
    }
}